---
# defaults/main.yml for datadog_incident_management

# Target host
datadog_incident_management_host: ""

# Authentication
datadog_incident_management_username: ""
datadog_incident_management_password: ""
datadog_incident_management_api_key: ""

# Behavior
datadog_incident_management_validate_certs: true
datadog_incident_management_state: present
