---
namespace: stevefulme1
name: datadog
version: 0.1.0
readme: README.md
authors:
  - Steve Fulmer (@stevefulme1)
description: Ansible collection for the Datadog API monitoring and observability
license:
  - GPL-3.0-or-later
tags:
  - datadog
  - api
  - v1
  - collection
repository: https://github.com/stevefulme1/ansible-datadog
build_ignore:
  - tests/output
  - .tox
  - .venv
