---
# defaults/main.yml for datadog_security_monitoring

# Target host
datadog_security_monitoring_host: ""

# Authentication
datadog_security_monitoring_username: ""
datadog_security_monitoring_password: ""
datadog_security_monitoring_api_key: ""

# Behavior
datadog_security_monitoring_validate_certs: true
datadog_security_monitoring_state: present
