---
# defaults/main.yml for datadog_monitor_setup

# Target host
datadog_monitor_setup_host: ""

# Authentication
datadog_monitor_setup_username: ""
datadog_monitor_setup_password: ""
datadog_monitor_setup_api_key: ""

# Behavior
datadog_monitor_setup_validate_certs: true
datadog_monitor_setup_state: present
