---
# defaults/main.yml for datadog_log_pipeline

# Target host
datadog_log_pipeline_host: ""

# Authentication
datadog_log_pipeline_username: ""
datadog_log_pipeline_password: ""
datadog_log_pipeline_api_key: ""

# Behavior
datadog_log_pipeline_validate_certs: true
datadog_log_pipeline_state: present
